LightProject/config/routes.rb
Rails.application.routes.draw do
  resources :rules
  resources :actors
  resources :sensors

end

LightProject/app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :rule
  belongs_to :actor
end

LightProject/app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :actions
end

LightProject/app/models/condition.rb
class Condition < ActiveRecord::Base
  belongs_to :sensor
  belongs_to :rule
end

LightProject/app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :sensor
  belongs_to :condition
  belongs_to :action
end

LightProject/app/models/sensor.rb
class Sensor < ActiveRecord::Base
  has_many :conditions
end

LightProject/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :description, :defaultSettings, :settings)
    end
end

LightProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

LightProject/app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:name, :description, :state, :conditionType, :sensor_id, :condition_id, :action_id)
    end
end

LightProject/app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :description)
    end
end

LightProject/app/helpers/actors_helper.rb
module ActorsHelper
end

LightProject/app/helpers/application_helper.rb
module ApplicationHelper
end

LightProject/app/helpers/rules_helper.rb
module RulesHelper
end

LightProject/app/helpers/sensors_helper.rb
module SensorsHelper
end

LightProject/app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :defaultSettings %><br>
    <%= f.text_area :defaultSettings %>
  </div>
  <div class="field">
    <%= f.label :settings %><br>
    <%= f.text_area :settings %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

LightProject/app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

LightProject/app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Defaultsettings</th>
      <th>Settings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.description %></td>
        <td><%= actor.defaultSettings %></td>
        <td><%= actor.settings %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

LightProject/app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

LightProject/app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @actor.description %>
</p>

<p>
  <strong>Defaultsettings:</strong>
  <%= @actor.defaultSettings %>
</p>

<p>
  <strong>Settings:</strong>
  <%= @actor.settings %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

LightProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LightProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

LightProject/app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="field">
    <%= f.label :conditionType %><br>
    <%= f.text_area :conditionType %>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br>
    <%= f.text_field :sensor_id %>
  </div>
  <div class="field">
    <%= f.label :condition_id %><br>
    <%= f.text_field :condition_id %>
  </div>
  <div class="field">
    <%= f.label :action_id %><br>
    <%= f.text_field :action_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

LightProject/app/views/rules/edit.html.erb
<h1>Editing Rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

LightProject/app/views/rules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>State</th>
      <th>Conditiontype</th>
      <th>Sensor</th>
      <th>Condition</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.name %></td>
        <td><%= rule.description %></td>
        <td><%= rule.state %></td>
        <td><%= rule.conditionType %></td>
        <td><%= rule.sensor %></td>
        <td><%= rule.condition %></td>
        <td><%= rule.action %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

LightProject/app/views/rules/new.html.erb
<h1>New Rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

LightProject/app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rule.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rule.description %>
</p>

<p>
  <strong>State:</strong>
  <%= @rule.state %>
</p>

<p>
  <strong>Conditiontype:</strong>
  <%= @rule.conditionType %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @rule.sensor %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @rule.condition %>
</p>

<p>
  <strong>Action:</strong>
  <%= @rule.action %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>

LightProject/app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

LightProject/app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

LightProject/app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.name %></td>
        <td><%= sensor.description %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td class="destroySensorBtn"><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

LightProject/app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

LightProject/app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sensor.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sensor.description %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>